<message>
    <header>
        <msgName>COMMAND_REQUEST</msgName>
        <transactionId>2f48f241-9d64-4d16-bf56-70b9d4e0e79a</transactionId>
        <sender>AGV_10</sender>
        <receiver>ACS</receiver>
        <firstTryTime>2024-05-02 09:55:00.123</firstTryTime>
    </header>
    <body>
        <commandType>LOAD</commandType>
        <side>LEFT</side>
        <agvStage>2</agvStage>
        <carrierType>BOX</carrierType>
        <carrierCount>3</carrierCount>
        <destination>1030</destination>
        <portId>PORT_01</portId>
    </body>
    <return>
        <returnCode>0</returnCode>
        <returnMsg/>
    </return>
</message>